import { PublicKey, SimulateTransactionConfig } from '@solana/web3.js';
export declare const TOKEN_LIST_API_URL = "https://token.jup.ag/all";
export declare const SwapChillApi: () => any;
export declare const SwapJupiterApi: () => any;
export declare const SwapJupiterQuoteApi = "https://quote-api.jup.ag/v6";
export declare const SwapApi: () => any;
export declare const OUT_TIME = 2500;
export declare const PROGRAMID: () => any;
export declare const commissionSignatureAddress: () => any;
export declare const AssociateTokenProgram = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL";
export declare const AddressTable = "5ZF8nmsRMPB24j5UDU7ztjvxVBJ7pprZJvzbujZ5nKpQ";
export declare const TOKEN_2022_OWNER = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb";
export declare const simulateConfig: SimulateTransactionConfig;
export declare const SEED_SWAP = "chill_swap";
export declare const SEED_DATA = "chill_data";
export declare const SEED_TRADE = "trade_config_data";
export declare const SEED_NONCE = "nonce_data";
export declare const WSOL_MINT: PublicKey;
export declare const SUPPORT_CHANGE_PROGRAM_IDS: Map<string, number>;
export declare const NEED_CHANGE_SLIPPAGE_PROGRAM_IDS: string[];
export declare const TOKEN_PROGRAM_OWNS: string[];
export declare const JITO_FEE_ACCOUNT: string[];
export declare const HIDEX_ADDRESS_LOOK_UP: PublicKey;
export declare const SOLANA_SYSTEM_PROGRAM_ID: PublicKey;
export declare const PUMP_PROGRAM_ID: PublicKey;
export declare const JUPITER_PROGRAM_ID: PublicKey;
export declare const PUMP_AMM_PROGRAM_ID: PublicKey;
export declare const PUMP_AMM_PROGRAM_ID2: PublicKey;
export declare const GMGN_PRIORITY_FEE_Collect_ID: PublicKey;
export declare const PUEM_INSTRUCTION_PREFIX = "66063d1201daebea";
export declare const SOLANA_SYSTEM_PROGRAM_TRANSFER_ID = 2;
export declare const SOLANA_CREATE_ACCOUNT_WITH_SEED_ID = 3;
export declare const SOLANA_MAX_TX_SERIALIZE_SIGN = 1160;
export declare const DEFAULT_SWAP_SOL_LAMPORTS: bigint;
export declare const DEFAULT_SWAP_PUMP_LAMPORTS: bigint;
export declare const BASE_ACCOUNT_INIT_FEE: bigint;
export declare const TIP_MINI_IN_PRIORITY: bigint;
export declare const DEFAULD_SOLANA_SWAP_LIMIT: number;
export declare const DEFAULD_SOLANA_GAS_LIMIT: number;
export declare const PREPARE_SOLANA_GAS_LIMIT: number;
export declare const COMMISSION_SOLANA_GAS_LIMIT: number;
export declare const DEFAULD_BASE_GAS_FEE: number;
export declare const VERSION_TRANSACTION_PREFIX = "AQAAAAAAA";
export declare const PRE_PAID_EXPENSES: number;
export declare const QUIKNODE_SEND_URL: string[];
export declare const JITO_SEND_URL: string[];
//# sourceMappingURL=config.d.ts.map