import { Keypair, PublicKey, SimulateTransactionConfig } from '@solana/web3.js';
export declare const TOKEN_LIST_API_URL = "https://token.jup.ag/all";
export declare const SwapChillApi: () => any;
export declare const SwapJupiterApi: () => any;
export declare const SwapJupiterQuoteApi = "https://quote-api.jup.ag/v6";
export declare const SwapApi: () => any;
export declare const OUT_TIME = 2500;
export declare const PROGRAMID: () => any;
export declare const commissionSignatureAddress: () => any;
export declare const AssociateTokenProgram = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL";
export declare const AddressTable = "5ZF8nmsRMPB24j5UDU7ztjvxVBJ7pprZJvzbujZ5nKpQ";
export declare const TOKEN_2022_OWNER = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb";
export declare const simulateConfig: SimulateTransactionConfig;
export declare const ownerKeypair: (key: string) => Keypair;
export declare const owner: Keypair;
export declare const SEED_SWAP = "chill_swap";
export declare const SEED_DATA = "chill_data";
export declare const SEED_TRADE = "trade_config_data";
export declare const SUPPORT_CHANGE_PROGRAM_IDS: string[];
export declare const SUPPORT_CHANGE_INSTRUCTION_START_INDEXES: number[];
export declare const HIDEX_ADDRESS_LOOK_UP: PublicKey;
export declare const SOLANA_SYSTEM_PROGRAM_ID: PublicKey;
export declare const PUMP_PROGRAM_ID: PublicKey;
export declare const GMGN_PRIORITY_FEE_Collect_ID: PublicKey;
export declare const PUEM_INSTRUCTION_PREFIX = "66063d1201daebea";
export declare const SOLANA_SYSTEM_PROGRAM_TRANSFER_ID = 2;
export declare const SOLANA_CREATE_ACCOUNT_WITH_SEED_ID = 3;
export declare const DEFAULT_SWAP_SOL_LAMPORTS: bigint;
export declare const BASE_ACCOUNT_INIT_FEE: bigint;
//# sourceMappingURL=config.d.ts.map